"use client";
import {useEffect,useMemo,useState} from "react";
const INGRESO_ID="75942fa8-9bea-4207-93a8-fe4c53484500";
type Summary={turns_today:number;waiting:number;finished:number;absent:number;cancelled:number;avg_wait_minutes:number;avg_service_minutes:number;by_sector:Array<{sector_id:string;sector:string;waiting:number;today:number}>};
type Row=Record<string,unknown>;type Box={id:string;code:string;name:string;active:boolean;floor?:string;location?:string};type Category={id:string;name:string;prefix:string;active:boolean;target_minutes?:number};type User={id:string;username:string;display_name:string;role:string;active:boolean;last_login_at?:string};type Config={boxes:Box[];categories:Category[];users:User[]};type Tab="resumen"|"atencion"|"turnos"|"operadores"|"boxes"|"categorias"|"estadisticas";
function today(){return new Date().toISOString().slice(0,10)}function csvEscape(v:unknown){const s=v==null?"":String(v);return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
export default function AdminClient(){
 const[tab,setTab]=useState<Tab>("resumen"),[summary,setSummary]=useState<Summary|null>(null),[config,setConfig]=useState<Config|null>(null),[rows,setRows]=useState<Row[]>([]),[from,setFrom]=useState(today()),[to,setTo]=useState(today()),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 async function request(url:string,init?:RequestInit){const res=await fetch(url,{cache:'no-store',...init}),json=await res.json();if(res.status===401)throw new Error('Iniciá sesión desde Operadores con un usuario administrador');if(!res.ok||!json.ok)throw new Error(json.error||'No se pudieron cargar los datos');return json.data}
 async function loadSummary(){setSummary(await request('/api/admin/summary'))}async function loadConfig(){setConfig(await request(`/api/admin/configuration?sectorId=${INGRESO_ID}`))}async function loadReport(){setLoading(true);setError('');try{const qs=new URLSearchParams({from,to,sectorId:INGRESO_ID});setRows(await request(`/api/admin/report?${qs}`)||[])}catch(e){setError(e instanceof Error?e.message:'No se pudo cargar el informe')}finally{setLoading(false)}}
 async function save(url:string,body:unknown){setSaving(true);setError('');setNotice('');try{await request(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await loadConfig();setNotice('Cambios guardados correctamente.')}catch(e){setError(e instanceof Error?e.message:'No se pudieron guardar los cambios')}finally{setSaving(false)}}
 useEffect(()=>{Promise.all([loadSummary(),loadConfig(),loadReport()]).catch(e=>setError(e.message))},[]);const columns=useMemo(()=>rows.length?Object.keys(rows[0]):[],[rows]);function downloadCsv(){if(!rows.length)return;const csv=[columns.join(','),...rows.map(r=>columns.map(c=>csvEscape(r[c])).join(','))].join('\n'),blob=new Blob(["\ufeff"+csv],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`turnero_ingreso_${from}_${to}.csv`;a.click();URL.revokeObjectURL(url)}
 const tabs:Array<[Tab,string]>=[["resumen","Resumen"],["atencion","Atención"],["turnos","Turnos"],["operadores","Operadores"],["boxes","Boxes"],["categorias","Categorías"],["estadisticas","Estadísticas"]];
 return <><div className="adminnav">{tabs.map(([id,label])=><button key={id} className={tab===id?"button":"button secondary"} onClick={()=>setTab(id)}>{label}</button>)}</div>{error&&<div className="error-box">{error}</div>}{notice&&<div className="notice">{notice}</div>}
 {tab==="resumen"&&<div className="grid"><Metric label="Turnos de hoy" value={summary?.turns_today}/><Metric label="Finalizados" value={summary?.finished}/><Metric label="Esperando" value={summary?.waiting}/><Metric label="Espera promedio" value={`${summary?.avg_wait_minutes??'—'} min`}/><Metric label="Atención promedio" value={`${summary?.avg_service_minutes??'—'} min`}/><Metric label="Ausentes / cancelados" value={(summary?.absent??0)+(summary?.cancelled??0)}/></div>}
 {tab==="atencion"&&<section className="card"><h2>Atención de hoy</h2><p className="muted">Esperando: {summary?.waiting??0} · Finalizados: {summary?.finished??0} · Boxes activos: {config?.boxes.filter(b=>b.active).length??0}</p></section>}
 {tab==="turnos"&&<Report rows={rows} columns={columns} from={from} to={to} setFrom={setFrom} setTo={setTo} loading={loading} loadReport={loadReport} downloadCsv={downloadCsv}/>} 
 {tab==="operadores"&&<section className="card"><h2>Operadores de Ingreso</h2><div className="queue">{config?.users.map(u=><div className="row" key={u.id}><strong>{u.display_name}</strong><div>{u.username}</div><div>{u.role}</div><div>{u.active?'Activo':'Inactivo'}</div></div>)}</div></section>}
 {tab==="boxes"&&<section className="card"><h2>Boxes de Ingreso</h2><p className="muted">No se puede desactivar un box que tenga un turno activo.</p><div className="queue">{config?.boxes.map(b=><BoxLine key={b.id} box={b} saving={saving} save={x=>save('/api/admin/box',x)}/>)}</div></section>}
 {tab==="categorias"&&<section className="card"><h2>Categorías</h2><p className="muted">Prefijo: 2 a 5 letras/números. Tiempo objetivo: 1 a 240 minutos.</p><div className="queue">{config?.categories.map(c=><CategoryLine key={c.id} category={c} saving={saving} save={x=>save('/api/admin/category',x)}/>)}</div></section>}
 {tab==="estadisticas"&&<><div className="grid"><Metric label="Espera promedio" value={`${summary?.avg_wait_minutes??0} min`}/><Metric label="Atención promedio" value={`${summary?.avg_service_minutes??0} min`}/><Metric label="Turnos hoy" value={summary?.turns_today??0}/></div><Report rows={rows} columns={columns} from={from} to={to} setFrom={setFrom} setTo={setTo} loading={loading} loadReport={loadReport} downloadCsv={downloadCsv}/></>}</>}
function Metric({label,value}:{label:string;value:unknown}){return <section className="card span4"><div className="muted">{label}</div><div className="metric">{String(value??'—')}</div></section>}
function BoxLine({box,saving,save}:{box:Box;saving:boolean;save:(v:unknown)=>void}){const[name,setName]=useState(box.name),[active,setActive]=useState(box.active);return <div className="row"><strong>{box.code}</strong><input value={name} onChange={e=>setName(e.target.value)}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Activo</label><button className="button" disabled={saving} onClick={()=>save({servicePointId:box.id,name,active,floor:box.floor||'',location:box.location||''})}>Guardar</button></div>}
function CategoryLine({category,saving,save}:{category:Category;saving:boolean;save:(v:unknown)=>void}){const[name,setName]=useState(category.name),[prefix,setPrefix]=useState(category.prefix),[minutes,setMinutes]=useState(category.target_minutes||10),[active,setActive]=useState(category.active);return <div className="row"><input value={prefix} onChange={e=>setPrefix(e.target.value.toUpperCase())}/><input value={name} onChange={e=>setName(e.target.value)}/><input type="number" min={1} max={240} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><label><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Activa</label><button className="button" disabled={saving} onClick={()=>save({categoryId:category.id,name,prefix,targetMinutes:minutes,active})}>Guardar</button></div>}
function Report({rows,columns,from,to,setFrom,setTo,loading,loadReport,downloadCsv}:{rows:Row[];columns:string[];from:string;to:string;setFrom:(v:string)=>void;setTo:(v:string)=>void;loading:boolean;loadReport:()=>void;downloadCsv:()=>void}){return <section className="card" style={{marginTop:20}}><h2>Informe de atención</h2><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'end'}}><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><button className="button" onClick={loadReport} disabled={loading}>{loading?'Cargando…':'Aplicar filtros'}</button><button className="button secondary" onClick={downloadCsv} disabled={!rows.length}>Descargar CSV</button></div><p className="muted">{rows.length} registros.</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',fontSize:13}}><thead><tr>{columns.map(c=><th key={c} style={{textAlign:'left',padding:8}}>{c}</th>)}</tr></thead><tbody>{rows.slice(0,100).map((r,i)=><tr key={i}>{columns.map(c=><td key={c} style={{padding:8}}>{r[c]==null?'':String(r[c])}</td>)}</tr>)}</tbody></table></div></section>}
